version: '3.0'
services:

  erpnext-demo:
    image: siggraph/erpnext:1.0.2  # Replace with your actual producer app image
    container_name: erpnext-demo
    hostname: erpnext-demo
    volumes:
      - ./docker-sites:/home/frappe/erpnext/erpnext/sites
    networks:
      - erpnext-network
    user: frappe
    working_dir: /home/frappe/erpnext
    #command: bash -c "source ./demo/run-demo.sh && sleep infinity"
    command: sleep infinity

networks:
  erpnext-network:
    driver: bridge