version: '3.0'
services:
  redis:
    image: redis:7.2.0-alpine
    hostname: redis
    volumes:
      - ./redis:/usr/local//etc/redis
    ports:
      - 6380:6379
  db:
    image: mariadb:10.6.15-focal
    hostname: db
    volumes: 
      - ./data/db:/var/lib/mysql
      - ./mariadb/config:/etc/mysql/conf.d
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=root
    ports:
      - 3306:3306
  # erpnext:
  #   image: python:3.10.16-slim-bookworm
  #   volumes:
  #     - ./:/root/temp
  #   command: sleep infinity