version: '3.0'
services:

  redis:
    image: redis:7.2.0-alpine
    hostname: redis
    volumes:
      - ./docker-redis:/usr/local//etc/redis
    ports:
      - 6381:6379
    networks:
      - erpnext-network
  db:
    image: mariadb:10.6.15-focal
    hostname: db
    volumes: 
      - ./docker-data/db:/var/lib/mysql
      - ./docker-mariadb/config:/etc/mysql/conf.d
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=root
    ports:
      - 3307:3306
    networks:
      - erpnext-network

  erpnext-demo:
    image: asia-southeast1-docker.pkg.dev/siggraph-453519/erpnext/erpnext:latest
    container_name: erpnext-demo
    hostname: erpnext-demo
    volumes:
      - ./docker-sites:/home/frappe/erpnext/erpnext/sites
      - ./demo:/home/frappe/erpnext/demo
      - ./new-site.sh:/home/frappe/erpnext/new-site.sh
    networks:
      - erpnext-network
    user: frappe
    working_dir: /home/frappe/erpnext
    command: bash -c "source ./demo/run-demo.sh && sleep infinity"
    #command: sleep infinity

networks:
  erpnext-network:
    driver: bridge
    name: erpnext-network